#Describing the models in this schema
version: 2

models:

    - name: stg_pageviews_incremental
      description: "A materialized incremental table of pageviews"
      columns:
          - name: user_id
            description: "The identifier for a user"
            tests:
                - not_null
          - name: pageview_hour
            description: 'The truncated hour of the time of the pageview'
          - name: count_pageviews
            description: 'An aggregation of number of views within the hour for that user'
          - name: hist_postcode
            description: 'The postcode of the user on the day of the view'

