#I have outlined the source data here, I put in placeholder values for the schema and tables

#Could also add tests to these tables to look for multiple user IDs appearing in the table or if there appears
#multiple hours of data within the pageviews table

version: 2

sources:
  - name: users_extract
    description: 'Sample user data provided by checkout'
    database: checkout_db
    warehouse: users_extract
    schema: raw
    tables:
      - name: users
        description: 'details of the users'
        columns:
          - name: id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: postcode
            description: "Postcode of user"

  - name: pageviews_extract
    description: 'sample pageview data provided by checkout'
    database: checkout_db
    warehouse: pageviews_extract
    schema: raw
    tables:
      - name: pageviews
        description: 'Sample pageview data provided by checkout'
        columns:
          - name: user_id
            description: "The primary key for this table"
            tests:
              - not_null
          - name: url
            description: "URL of webpage viewed"
          - name: pageview_datetime
            description: "time of pageview"

